version: '3'
services:
 db:
   image: mongo:3.7
   restart: always
   ports:
     - 27017:27017
   volumes:
     - ./data/volumes/mongo:/data/db

# redis:
#   image: redis:4.0.8
#   restart: always
#   ports:
#     - 6379:6379

 rabbitmq:
   image: rabbitmq:3.7.3-management
   restart: always
   volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
   ports:
     - "5672:5672"
     - "15672:15672"
   environment:
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: admin
